### ISSUE TITLE
Tests create data outside of ${project.build.directory}

### ISSUE THREAD

**Issue by rovarga** [PantheonTechnologies/lighty-core#140]
Running tests which include Clustered Datastore leaves its persistence scattered across the repository, which is not cleaned up after 'mvn clean'. That is clearly bad.

**Comment by jveverka** [comment]
The problem is that persistence directories are outside target directories are not deleted by 'mvn clean'. integration tests which are running lighty controllers (md-sal) should set persistence data path inside target directories.

**Comment by jveverka** [comment]
fixed, resolved
