### ISSUE TITLE
Import a Yang model on Lighty.io

### ISSUE THREAD

**Issue by matheusnicolas** [PantheonTechnologies/lighty-core#202]
I'm searching for forms to import a Yang model on Lighty.io but I can't import. How I do this?

**Comment by jveverka** [comment]
Check out this [0] guide, it should solve your peoblem. Let me know if it works.
[0] https://github.com/PantheonTechnologies/lighty-core/blob/9.2.x/lighty-models/README.md

**Comment by matheusnicolas** [comment]
Can you help me on how to use the Yang model to try some netconf request to a device?
