### ISSUE TITLE
Build of branch 11.2.x fails on missing dependency org.fusesource.leveldbjni:leveldbjni-all:jar:1.8-odl

### ISSUE THREAD

**Issue by chrisinmtown** [PantheonTechnologies/lighty-core#392]
I'm new to lighty and just trying to compile an example, specifically lighty-examples/lighty-controller-springboot-netconf.  I cloned the repo and tried "mvn compile" in the top-level directory, lighty-core.  I did NOT modify any of my maven settings files, and I see no repositories listed in the pom, all jars were downloaded from https://repo.maven.apache.org/maven2. The build soon ran aground with this error in the lighty-controller project:

`[ERROR] Failed to execute goal on project lighty-controller: Could not resolve dependencies for project io.lighty.core:lighty-controller:jar:11.2.1-SNAPSHOT: Failure to find org.fusesource.leveldbjni:leveldbjni-all:jar:1.8-odl in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
`

I checked https://repo.maven.apache.org/maven2/org/fusesource/leveldbjni/leveldbjni-all/ and found version 1.8 of this jar, but not version 1.8-odl.  

Please advise, thanks.

**Comment by chrisinmtown** [comment]
Found https://github.com/fusesource/leveldbjni which was last updated 2017 and says to use version 1.8.

**Comment by Pyro2266** [comment]
Hello, thank you for your comments.
We are currently using _settings.xml_ file to setup ODL repositories. There is a step-by-step guide how to build project in the _README.md_ file ([Build & Install](https://github.com/PantheonTechnologies/lighty-core/blob/11.2.x/README.md#build--install) section). It points to the _settings.xml_ file we are using.

**Comment by chrisinmtown** [comment]
It seems some work was done late 2019 on a different branch to use only publicly available jar files, here's the commit, maybe it will be propagated to the latest someday and that would probably address my concern

https://github.com/PantheonTechnologies/lighty-core/commit/ec605d96235fb3f3d1204e8c2822d87d78dac68f

**Comment by Pyro2266** [comment]
If you look at the pull requests, I actually cherry-picked that change to all active branches. It will be merged soon and buildable without any special maven config.

I wanted to let you know after it's merged, but you were faster.

**Comment by rovarga** [comment]
All branches have been updated.

**Comment by chrisinmtown** [comment]
Thanks @rovarga  and @Pyro2266!
