### ISSUE TITLE
Problems encountered while receiving Netconf notifications

### ISSUE THREAD

**Issue by dizang428** [PantheonTechnologies/lighty-core#417]
My project needed to receive notifications from the netconf device, but had problems registering listeners.
Send notice of my equipment successfully into the controller, and entered into the NetconfDeviceNotificationService.class, but in to the registered listener, I can't get NetconfDeviceNotificationService instance of this class, lead to publishNotification method to distribute notice, listeners have been empty.

Then I try to get NetconfDeviceNotificationService instance is found that in this class, NetconfDeviceSalFacade instance is like this new directly.
```
    @Override
    public synchronized void onDeviceConnected(final MountPointContext mountContext,
                                               final NetconfSessionPreferences netconfSessionPreferences,
                                               final DOMRpcService deviceRpc, final DOMActionService deviceAction) {
        final SchemaContext schemaContext = mountContext.getSchemaContext();
        final NetconfDeviceDataBroker netconfDeviceDataBroker =
                new NetconfDeviceDataBroker(id, schemaContext, deviceRpc, netconfSessionPreferences);
        registerLockListener(netconfDeviceDataBroker);
        final NetconfDeviceNotificationService notificationService = new NetconfDeviceNotificationService();

        salProvider.getMountInstance()
                .onTopologyDeviceConnected(schemaContext, netconfDeviceDataBroker, deviceRpc, notificationService,
                        deviceAction);
        salProvider.getTopologyDatastoreAdapter()
                .updateDeviceData(true, netconfSessionPreferences.getNetconfDeviceCapabilities());
    }
```
I want to know how to get NetconfDeviceNotificationService instance and register the listener? Or can I use another class to get notifications from netconf devices?
thank you

**Comment by dizang428** [comment]
I used lighty-core v11.0.1, and I tried to register listeners in the following two ways, but without success.
    @Autowired
    private NotificationService notificationService;
    @Autowired
    private DOMNotificationService domNotificationService;
        notificationService.registerNotificationListener(new AccNotificationsListenerImpl());
        
        final BindingDOMNotificationListenerAdapter domListener
        = new BindingDOMNotificationListenerAdapter(bindingToNormalizedNodeCodec, new AccNotificationsListenerImpl());
        	final ListenerRegistration<BindingDOMNotificationListenerAdapter> domRegistration =
		domNotificationService.registerNotificationListener(domListener, domListener.getSupportedNotifications());

**Comment by dizang428** [comment]
I found a place to get an instance of netconfnotifyService

**Comment by wxiaobing** [comment]
> I found a place to get an instance of netconfnotifyService

where?
