### ISSUE TITLE
How could I find the UI component?

### ISSUE THREAD

**Issue by myonlystarWang** [PantheonTechnologies/lighty-core#451]
Hi all,
    I am new to lighty-core and I want to use the LIGHTY.IO UI NETWORK TOPOLOGY VISIBILITY COMPONENT which was introduced on the official website [https://lighty.io/network-topology-visualization-component/](https://lighty.io/network-topology-visualization-component/).And how to use it?
   It would be nice if someone could give me some pointers.

BR,
myonlystarWang

**Comment by mmiklus** [comment]
Dear myonlystarWang,

the topology visualization library is available for all customers who are using commercial lighty.io distribution.

**Please use https://lighty.io/contact/ to get more information.** 

Thank you,
-m-
